using System.ComponentModel;

namespace ImageUploaderAPI.Models.Enums
{
    public enum ImageMimeTypes
    {
        undefined,
        [Description("image/bmp")]
        bmp,
        [Description("image/vnd.djvu")]
        djv,
        [Description("image/vnd.djvu")]
        djvu,
        [Description("image/gif")]
        gif,
        [Description("image/x-icon")]
        ico,
        [Description("image/ief")]
        ief,
        [Description("image/jp2")]
        jp2,
        [Description("image/jpeg")]
        jpe,
        [Description("image/jpeg")]
        jpeg,
        [Description("image/jpeg")]
        jpg,
        [Description("image/x-macpaint")]
        mac,
        [Description("image/x-portable-bitmap")]
        pbm,
        [Description("image/pict")]
        pct,
        [Description("image/pict")]
        pic,
        [Description("image/pict")]
        pict,
        [Description("image/png")]
        png,
        [Description("image/x-portable-anymap")]
        pnm,
        [Description("image/x-macpaint")]
        pnt,
        [Description("image/x-macpaint")]
        pntg,
        [Description("image/x-portable-pixmap")]
        ppm,
        [Description("image/x-quicktime")]
        qti,
        [Description("image/x-quicktime")]
        qtif,
        [Description("image/x-cmu-raster")]
        ras,
        [Description("image/x-rgb")]
        rgb,
        [Description("image/tiff")]
        tif,
        [Description("image/tiff")]
        tiff,
        [Description("image/vnd.wap.wbmp")]
        wbmp,
        [Description("image/x-xbitmap")]
        xbm,
        [Description("image/x-xpixmap")]
        xpm,
        [Description("image/x-xwindowdump")]
        xwd
    }
}
